# Generated by Django 5.2.1 on 2025-05-30 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('group_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('delete_datetime', models.DateTimeField(null=True)),
                ('is_delete', models.BooleanField(default=0)),
                ('project_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('project_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_status', models.CharField(max_length=30)),
                ('mcmc_current_task_id', models.CharField(max_length=100, null=True)),
                ('simulation_current_task_id', models.CharField(max_length=100, null=True)),
                ('simulations_list', models.CharField(max_length=500, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('delete_datetime', models.DateTimeField(null=True)),
                ('is_delete', models.BooleanField(default=0)),
                ('is_publish', models.BooleanField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
            ],
        ),
        migrations.CreateModel(
            name='mmm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agg_chnl_list', models.TextField()),
                ('segmentation_type', models.TextField()),
                ('parameters', models.TextField()),
                ('rawdata_unscaled_dict', models.TextField()),
                ('rawdata_scaled_dict', models.TextField()),
                ('digital_gsk_impute', models.TextField()),
                ('average_pirce_orig', models.TextField()),
                ('average_pirce_agg', models.TextField()),
                ('average_count_orig', models.TextField()),
                ('average_count_agg', models.TextField()),
                ('total_cost_sales_ratio', models.TextField()),
                ('cost_dist', models.TextField()),
                ('line_trend_dist', models.TextField()),
                ('extra_features_1', models.TextField()),
                ('r_square_mape', models.TextField()),
                ('channel_contribution', models.TextField()),
                ('base_contribution', models.TextField()),
                ('roi_mroi', models.TextField()),
                ('mmm', models.TextField()),
                ('last', models.BooleanField(default=1)),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projects')),
            ],
        ),
        migrations.CreateModel(
            name='rawdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('df_rawdata', models.TextField()),
                ('df_data_ab_others', models.TextField()),
                ('df_mccp', models.TextField()),
                ('brand_name', models.CharField()),
                ('time_period_id', models.CharField()),
                ('data_version_id', models.CharField()),
                ('ori_channel_list', models.TextField()),
                ('ori_channel_prior', models.TextField()),
                ('ori_segment', models.TextField()),
                ('last', models.BooleanField(default=1)),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projects')),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('role', models.IntegerField(choices=[(1, 'Guest'), (2, 'Maintainer'), (3, 'Owner')], default=1)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('delete_datetime', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=1)),
                ('roleoptions', models.CharField(null=True)),
                ('activity', models.CharField(null=True)),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.role'),
        ),
        migrations.AddField(
            model_name='group',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.role'),
        ),
        migrations.CreateModel(
            name='share',
            fields=[
                ('pk', models.CompositePrimaryKey('role_id', 'projects_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('msg', models.CharField(null=True)),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projects')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.role')),
            ],
        ),
        migrations.CreateModel(
            name='simulation',
            fields=[
                ('pk', models.CompositePrimaryKey('simulation_name', 'projects_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('simulation_name', models.CharField()),
                ('optimization_type', models.TextField()),
                ('parameters', models.TextField(null=True)),
                ('optimization_output', models.TextField(null=True)),
                ('optimal_channel_performance', models.TextField(null=True)),
                ('current_channel_performence', models.TextField(null=True)),
                ('simulated_promotion_base', models.TextField(null=True)),
                ('simulated_channel_contribution', models.TextField(null=True)),
                ('simulated_roi_mroi', models.TextField(null=True)),
                ('simulated_cost_dist', models.TextField(null=True)),
                ('simulated_unit_price', models.TextField(null=True)),
                ('last', models.BooleanField(default=1)),
                ('is_visible', models.BooleanField(default=1)),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projects')),
            ],
        ),
    ]
