# Generated by Django 5.2.1 on 2025-06-04 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='projects',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.projects'),
        ),
    ]
