# Generated by Django 5.2.1 on 2025-06-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_rawdata_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='df_input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_version_id', models.IntegerField()),
                ('inst_code', models.CharField(max_length=500)),
                ('yyyymm', models.IntegerField()),
                ('brand_en', models.CharField(max_length=500)),
                ('sum_sales_vol', models.FloatField()),
                ('sum_sales_val', models.FloatField()),
                ('f2f_tp', models.FloatField()),
                ('f2f_cost', models.FloatField()),
                ('f2f_cost_direct', models.FloatField()),
                ('ht_tp', models.FloatField()),
                ('ht_cost', models.FloatField()),
                ('ht_cost_direct', models.FloatField()),
                ('standalone_offline_tp', models.FloatField()),
                ('standalone_offline_cost', models.FloatField()),
                ('standalone_offline_cost_direct', models.FloatField()),
                ('standalone_online_tp', models.FloatField()),
                ('standalone_online_cost', models.FloatField()),
                ('standalone_online_cost_direct', models.FloatField()),
                ('collaboration_offline_tp', models.FloatField()),
                ('collaboration_offline_cost', models.FloatField()),
                ('collaboration_offline_cost_direct', models.FloatField()),
                ('collaboration_online_tp', models.FloatField()),
                ('collaboration_online_cost', models.FloatField()),
                ('collaboration_online_cost_direct', models.FloatField()),
                ('sponsor_tp', models.FloatField()),
                ('sponsor_cost', models.FloatField()),
                ('sponsor_cost_direct', models.FloatField()),
                ('iengage_tp', models.FloatField()),
                ('iengage_cost', models.FloatField()),
                ('iengage_cost_direct', models.FloatField()),
                ('push_tp', models.FloatField()),
                ('push_cost', models.FloatField()),
                ('push_cost_direct', models.FloatField()),
                ('pvuv_tp', models.FloatField()),
                ('pvuv_cost', models.FloatField()),
                ('pvuv_cost_direct', models.FloatField()),
                ('digital_third_tp', models.FloatField()),
                ('digital_third_cost', models.FloatField()),
                ('digital_third_cost_direct', models.FloatField()),
                ('segment_type_1', models.IntegerField()),
                ('segment_type_2', models.IntegerField()),
                ('segment_type_3', models.IntegerField()),
                ('segment_type_4', models.IntegerField()),
            ],
        ),
    ]
