# Generated by Django 5.2.1 on 2025-06-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_df_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='ori_channel_list',
            field=models.TextField(default={'collaboration_offline': 7, 'collaboration_online': 5, 'digital_gsk': 2, 'digital_third': 3, 'f2f': 0, 'ht': 1, 'sponsor': 8, 'standalone_offline': 6, 'standalone_online': 4}),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='ori_channel_prior',
            field=models.TextField(default={'channel_name': ['f2f', 'ht', 'digital_gsk', 'digital_third', 'standalone_online', 'collaboration_online', 'standalone_offline', 'collaboration_offline', 'sponsor'], 'channel_prior': [0.56, 0.76, 0.53, 0.52, 0.68, 0.68, 0.71, 0.71, 0.75]}),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='ori_segment',
            field=models.TextField(default={'segment_type_1': {'Core': 1, 'Engine': 2, 'Others': 3, 'Total_market': 0}, 'segment_type_2': {'Central': 1, 'Others': 3, 'Regional': 2, 'Total_market': 0}, 'segment_type_3': {'Lupus_Center': 1, 'Others': 2, 'Total_market': 0}, 'segment_type_4': {'Lupus_Certification_Center': 1, 'Lupus_Demonstration_Center': 2, 'Others': 3, 'Total_market': 0}}),
        ),
    ]
