# Generated by Django 5.2.1 on 2025-06-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_rawdata_ori_channel_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='df_abothers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_version_id', models.IntegerField()),
                ('yyyymm', models.IntegerField()),
                ('brand_en', models.CharField(max_length=500)),
                ('f2f_total', models.IntegerField()),
                ('f2f_ab', models.IntegerField()),
                ('ht_total', models.IntegerField()),
                ('ht_ab', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='df_cd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=250)),
                ('impact_factor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='df_mccp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yyyymm', models.IntegerField()),
                ('brand_en', models.CharField(max_length=500)),
                ('f2f', models.FloatField()),
                ('ht', models.FloatField()),
                ('iengage', models.FloatField()),
                ('ratio', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='time_period_id',
        ),
        migrations.AddField(
            model_name='rawdata',
            name='yyyymm_end',
            field=models.IntegerField(default=202412),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='data_version_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='ori_channel_prior',
            field=models.TextField(),
        ),
    ]
