# Generated by Django 5.2.1 on 2025-06-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_df_abothers_df_cd_df_mccp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='df_cd',
            name='data_version_id',
            field=models.IntegerField(default=20250501),
            preserve_default=False,
        ),
    ]
